"""Initial setup

Revision ID: 16d77b72916f
Revises: 
Create Date: 2026-07-29 22:23:41.676441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16d77b72916f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('complaint_source', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_strength', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity_affected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('complaint_type', sa.String(length=100), nullable=True),
    sa.Column('complaint_date', sa.Date(), nullable=True),
    sa.Column('complaint_description', sa.Text(), nullable=True),
    sa.Column('initial_severity', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('ai_extraction_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('source_document_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_complaints_batch_number', 'complaints', ['batch_number'], unique=False)
    op.create_index('idx_complaints_complaint_date', 'complaints', ['complaint_date'], unique=False)
    op.create_index('idx_complaints_product_name', 'complaints', ['product_name'], unique=False)
    op.create_index('idx_complaints_status', 'complaints', ['status'], unique=False)
    op.create_table('ai_extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('raw_extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capa_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=100), nullable=True),
    sa.Column('root_cause_text', sa.Text(), nullable=True),
    sa.Column('recommended_corrective_action', sa.Text(), nullable=True),
    sa.Column('recommended_preventive_action', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicate_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('potential_duplicate_id', sa.UUID(), nullable=True),
    sa.Column('similarity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['potential_duplicate_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_matches')
    op.drop_table('complaint_attachments')
    op.drop_table('chat_messages')
    op.drop_table('capa_recommendations')
    op.drop_table('audit_trail')
    op.drop_table('ai_extraction_runs')
    op.drop_index('idx_complaints_status', table_name='complaints')
    op.drop_index('idx_complaints_product_name', table_name='complaints')
    op.drop_index('idx_complaints_complaint_date', table_name='complaints')
    op.drop_index('idx_complaints_batch_number', table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
